# docker-compose.yml
services:
  db:
    image: postgres:15 # Or your preferred version
    container_name: qltc_db # Keep original name for data volume consistency
    restart: always
    env_file:
      - ./qltc-backend/.env.production # Use production env file
    environment:
      POSTGRES_USER: ${DB_USER:-youruser} # Updated to match your .env
      POSTGRES_PASSWORD: ${DB_PASSWORD:-yourpassword} # Updated
      POSTGRES_DB: ${DB_NAME:-qltc_db} # Updated
    ports:
      - "5433:5432" # Expose DB port to host on 5433 for Docker deployment
    volumes:
      - qltc_db_data:/var/lib/postgresql/data # Use the existing development data volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-youruser} -d ${DB_NAME:-qltc_db}"] # Updated
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./qltc-backend # Path to your backend Dockerfile
      dockerfile: Dockerfile.prod # Use production Dockerfile
    container_name: qltc_backend_prod
    restart: always
    env_file:
      - ./qltc-backend/.env.production # Use production env file
    ports:
      - "3001:3000" # Expose backend port to host on 3001 for Docker deployment
    environment:
      # Ensure these match your .env or actual values
      DATABASE_URL: postgresql://${DB_USER:-youruser}:${DB_PASSWORD:-yourpassword}@db:5432/${DB_NAME:-qltc_db}?schema=public # Updated
      # For CORS in backend (main.ts and notifications.gateway.ts)
      FRONTEND_URL: http://192.168.1.165:8081 # Frontend will be on port 8081
      NODE_ENV: production
      # Add any other backend environment variables here
      JWT_SECRET: KKK
    depends_on:
      db:
        condition: service_healthy # Wait for DB to be ready

  frontend:
    build:
      context: ./qltc-app # Path to your frontend Dockerfile
      dockerfile: Dockerfile.prod # Use production Dockerfile
      args:
        # This VITE_API_BASE_URL will be used during the Quasar build process inside Docker
        # For local prod-like setup, the frontend needs to know the host-exposed backend URL
        VITE_API_BASE_URL: http://localhost:3001
        VITE_FORCE_DEV_USER: "true" # Ensures dev user mode for Docker builds
    container_name: qltc_frontend_prod
    restart: always
    ports:
      - "8081:80" # Expose frontend to host on 8081 for Docker deployment
    depends_on:
      - backend

volumes:
  qltc_db_data: # Define the existing data volume
